import '../globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from '@/components/modules/Header/index';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout(props: { children: React.ReactNode; booking: React.ReactNode; map: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Header />
                <main className="w-full h-full grid grid-cols-5 gap-4">
                    <section className="col-span-2">{props.booking}</section>
                    <section className="col-span-3">{props.map}</section>
                    {/* {props.children} */}
                </main>
            </body>
        </html>
    );
}

